source("acf_func.R")
source("sm_series.R")

set.seed(1111)
series = ARMA_func(c(0.7), NULL, 36)
# (a)
thm_acf = AR1_thm_acf(c(0.7))
draw_acf(thm_acf)
# (b)
(acf = acf_func(series))
draw_acf(acf,type="样本自相关")
cor(acf[1:20],thm_acf)
# (e)
pacf=pacf_func(series)
draw_pacf(pacf,n=36)
