source("acf_func.R")
source("sm_series.R")
set.seed(666)
series = ARMA_func(NULL,c(0.7,-0.4), 72)
# (a)
(thm_acf = MA_thm_acf(c(0.7,-0.4)))
# (b)
(acf = acf_func(series))
acf(series)
draw_acf(acf[1:20],type="样本自相关",n=72)
# (c)
series = ARMA_func(NULL,c(0.7,-0.4), 1000)
pacf=pacf_func(series,40)
draw_pacf(pacf,n=1000)
# (d)
pacf=pacf_func(series)
draw_pacf(pacf,n=72)
